### ISSUE TITLE
Segfault under OpenBSD 5.6/i386

### ISSUE THREAD

**Issue by vaygr** [jvinet/knock#15]
I've found an issue in knockd after upgrading from OpenBSD 5.5 to 5.6 on i386.
It started to crash on every second knock try.

Backtrace is here (running with '-D' flag):
```
----
2014-10-19 00:09:08: XXp: 195.9.XXX.XXX:36396 -> 85.30.XXX.XXX:M 74 bytes
2014-10-19 00:09:08: XXp: 195.9.XXX.XXX:38268 -> 85.30.XXX.XXX:N 60 bytes
2014-10-19 00:09:08: XXp: 195.9.XXX.XXX:34122 -> 85.30.XXX.XXX:P 74 bytes
[New process 4729]
0
2014-10-19 00:09:09: tcp: 195.9.XXX.XXX:36398 -> 85.30.XXX.XXX:M 74 bytes

removing successful knock attempt (195.9.XXX.XXX)

Program received signal SIGSEGV, Segmentation fault.
sniff (arg=0x0, hdr=0x7fd27000, packet=0x7fd27012 "") at src/knockd.c:1444
1444                    attempt = (knocker_t*)lp->data;
(gdb) bt
#0  sniff (arg=0x0, hdr=0x7fd27000, packet=0x7fd27012 "") at src/knockd.c:1444
#1  0x0a3a52cd in pcap_read (p=0x8440a000, cnt=-1, callback=0x1ab20550 <sniff>, user=0x0) at /usr/src/lib/libpcap/pcap-bpf.c:188
#2  0x0a3a3bed in pcap_dispatch (p=0x8440a000, cnt=-1, callback=0x1ab20550 <sniff>, user=0x0) at /usr/src/lib/libpcap/pcap.c:59
#3  0x1ab2114d in main (argc=536921060, argv=0x81944200) at src/knockd.c:270
----
```

After some digging I've found these lines:
```
list_free(lp);
continue;
```
But shouldn't we use 'break' here to prevent further reference to already freed 'lp' (and therefore 'lp->next') in the next iteration of 'for' cycle:
```
for(lp = attempts; lp; lp = lp->next)
```
after we totally free 'lp' recursively in list.c:
```
if(list->next != NULL) {
        list_free(list->next);
}
```
? Or did I miss/misunderstand something?

knock is compiled by GCC 4.2.1 with these flags: '-g -Wall -pedantic -fno-exceptions -O2 -pipe'.

**Comment by airwoflgh** [comment]
I've bundled the fixes under Issue #16 into my fork.
